### PR TITLE
Add option to specify download folder

### PR DESCRIPTION
**Pull request by s-l-teichmann**
Solves #398

### CODE REVIEW

**Review by JanHoefelmeyer — APPROVED** [review]
LGTM & works

**Review by bernhardreiter — DISMISSED** [review]
Good enough to go in.

The documentation for the option can be improved in a new PR to make clear that it is a folder relative to the DIR and to fix the minor spelling issue in `are stored in folder name by the year`.

**Review by bernhardreiter — APPROVED** [review]
LGTM

**Review by JanHoefelmeyer — APPROVED** [review]
lgtm & works

**Pull request merged**
