### PR TITLE
Downloader: ignore advisories by given patterns

### PR DESCRIPTION
**Pull request by s-l-teichmann**
Part of #140

### CODE REVIEW

**Review by JanHoefelmeyer — APPROVED** [review]
LGTM & works

**Review by JanHoefelmeyer — APPROVED** [review]

**Review by JanHoefelmeyer — DISMISSED** [review]
lgtm & works

**Review by JanHoefelmeyer — APPROVED** [review]
LGTM & Works

**Review by JanHoefelmeyer — DISMISSED** [review]
LGTM & works

**Review by bernhardreiter — APPROVED** [review]
LGTM

**Review by JanHoefelmeyer — APPROVED** [review]
LGTM & works

**Pull request merged**
