### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by s-l-teichmann**
Update dependencies

### CODE REVIEW

**Review by bernhardreiter — APPROVED** [review]
LGTM (build and looked at itest results which are working)

**Review by tschmidtb51 — APPROVED** [review]
LGTM

**Comment by tschmidtb51** [comment]
@s-l-teichmann: Based on the commit history: Was there an update issue? (No need to explain it here - just do it in our next meeting...)

**Comment by s-l-teichmann** [comment]
> @s-l-teichmann: Based on the commit history: Was there an update issue? (No need to explain it here - just do it in our next meeting...)

Yes, there are problems ... tracked in #345

**Pull request merged**
