### PR TITLE
Stop checker run of a domain after an error occurrs making a continua…

### PR DESCRIPTION
**Pull request by s-l-teichmann**
…tion pointless.

Fixes issue #24.

TODO: Improve handling of checks that are not run due to the stop.
They currently report success which is not correct.

### CODE REVIEW

**Comment by bernhardreiter** [comment]
Does the pr address the above todo or do we need another issue for this?

**Comment by s-l-teichmann** [comment]
@bernhardreiter No, it does not.

**Review by sthagen — COMMENTED** [review]
LGTM.

**Comment by s-l-teichmann** [comment]
@bernhardreiter #27 addresses the TODOs.

**Pull request merged**
