### PR TITLE
Document potential security issue with plain PEM passwords.

### PR DESCRIPTION
**Pull request by s-l-teichmann**
For #434

### CODE REVIEW

**Review by bernhardreiter — APPROVED** [review]
Okay as improvement. Phrasing can be improved.

**Review by JanHoefelmeyer — APPROVED** [review]
LGTM

**Review by bernhardreiter — APPROVED** [review]
LGTM

**Review by JanHoefelmeyer — APPROVED** [review]
LGTM

**Review by JanHoefelmeyer — APPROVED** [review]
LGTM

**Review by bernhardreiter — APPROVED** [review]
LGTM

**Pull request merged**
