### PR TITLE
Integrity check the ROLIE feed advisory URLs, hashes and signatures.

### PR DESCRIPTION
**Pull request by s-l-teichmann**
Solves #75

### CODE REVIEW

**Comment by bernhardreiter** [comment]
One test, I've changed a value to
```json
"href": "https://localhost:8443/.well-known/csaf/white/2022/bsi-2022-0001.json.sha156"
```
and run the checker   "version": "0.9.2-15-ga179896" with `--verbose`, but got no message and the url above was also not tried.  Is this behaviour to be expected?

**Comment by s-l-teichmann** [comment]
> 



> One test, I've changed a value to
> 
> ```json
> "href": "https://localhost:8443/.well-known/csaf/white/2022/bsi-2022-0001.json.sha156"
> ```
> 
> and run the checker "version": "0.9.2-15-ga179896" with `--verbose`, but got no message and the url above was also not tried. Is this behaviour to be expected?

Yes, as it ends with .sha156 ... only files ending with .sh256 and .sha512 are considered for check sums.

**Comment by s-l-teichmann** [comment]
> ### second test
> 
> In another test I've renamed a signature file like this
> 
> ```shell
> mv /var/www/html/.well-known/csaf/white/2022/bsi-2022-0001.json.asc /var/www/html/.well-known/csaf/white/2022/bsi-2022-0001.json.asco
> ```
> 
> and changed the entry in ` /var/www/html/.well-known/csaf/white/csaf-feed-tlp-white.json` to match it.
> 
> The checker run tried the url, and reported no issues. This seems not perfectly right as https://docs.oasis-open.org/csaf/csaf/v2.0/csd02/csaf-v2.0-csd02.html#7119-requirement-19-signatures demand an "appropriate extension".

"rel" is "signature" in this case which is enough to identify it as a signature URL. The URL structure itself
is not check. I would prefer this to be checked in the schema, but we could add it in the checker.

> ### third test
> 
> Destroyed on hash, used a different signature file, checker run detected this:
> 
> ```
>     <dt><strong>Requirement 18: Integrity (failed)</strong></dt>
>     <dd>- ERROR: SHA256 hash of https://localhost:8443/.well-known/csaf/white/2022/bsi-2022-0001.json does not match https://localhost:8443/.well-known/csaf/white/2022/bsi-2022-0001.json.sha256.</dd>
> 
>     <dt><strong>Requirement 19: Signatures (failed)</strong></dt>
>     <dd>- ERROR: Signature of https://localhost:8443/.well-known/csaf/white/2022/bsi-2022-0001.json could not be verified.</dd>
> ```

Can you post what exactly is in your feed file, please.

**Comment by s-l-teichmann** [comment]
> #### Re first test
> 
> > as it ends with .sha156 ... only files ending with .sh256 and .sha512 are considered for check sums.
> 
> However it is given as relative 'hash' and the rel `signature` is considered, beside the "unusual" filename in the **second test**. Wouldn't it be consistent to either consider "unusual" filenames in both tests or i non?
> 
> And if the choice is made that an "unusual" filename is detected, but not considered, shouldn't it be a warning?
> #### Re third test
> 
> > > Destroyed on hash, used a different signature file,  checker run detected this
> > > [..]
> > > Can you post what exactly is in your feed file, please.
> 
> Irrelevant as the test result was as expected: It did the test and found out that it did not match in case of the hash and the signature. Sorry that I was not clear enough about it.

It issues more warnings now. Please re-test.

**Pull request merged**
