### PR TITLE
Be more verbose in case of signature check failures

### PR DESCRIPTION
**Pull request by s-l-teichmann**
Also simplify handling of signature keys. 

For #358

### CODE REVIEW

**Review by JanHoefelmeyer — DISMISSED** [review]
LGTM (Download attempt for working signatures unchanged, for signature check failure now also puts out a reason: Signature Verification Error: Invalid signature)

**Review by tschmidtb51 — CHANGES_REQUESTED** [review]
I came a cross a weird output:
```
{
          "num": 20,
          "description": "Public OpenPGP Key",
          "messages": [
            {
              "type": 0,
              "text": "No OpenPGP keys loaded."
            },
            {
              "type": 0,
              "text": "1 public OpenPGP key(s) loaded."
            }
          ]
        }
      ]
    }
  ],
  "version": "2.1.1-21-g7eadf00",
```
This wasn't the case before:
```
{
          "num": 20,
          "description": "Public OpenPGP Key",
          "messages": [
            {
              "type": 0,
              "text": "2 public OpenPGP key(s) loaded."
            }
          ]
        }
      ]
    }
  ],
  "version": "2.1.1-20-g3590cf1",
```

**Comment by s-l-teichmann** [comment]
> I came a cross a weird output:
> 
> ```
> {
>           "num": 20,
>           "description": "Public OpenPGP Key",
>           "messages": [
>             {
>               "type": 0,
>               "text": "No OpenPGP keys loaded."
>             },
>             {
>               "type": 0,
>               "text": "1 public OpenPGP key(s) loaded."
>             }
>           ]
>         }
>       ]
>     }
>   ],
>   "version": "2.1.1-21-g7eadf00",
> ```
> 
> This wasn't the case before:
> 
> ```
> {
>           "num": 20,
>           "description": "Public OpenPGP Key",
>           "messages": [
>             {
>               "type": 0,
>               "text": "2 public OpenPGP key(s) loaded."
>             }
>           ]
>         }
>       ]
>     }
>   ],
>   "version": "2.1.1-20-g3590cf1",
> ```

Good catch!
Commit 87ab2ed97dbb45e6575862091de90fba7b9a70c7 should solve this.

**Review by tschmidtb51 — APPROVED** [review]
LGTM and works

**Review by JanHoefelmeyer — APPROVED** [review]
LGTM

**Pull request merged**
