### PR TITLE
Enforce `application/json` when uploading advisories to provider.

### LINKED ISSUE #148: Reject other than application/json content-types
When trying to upload an advisory, the `csaf_provider` should reject documents which are not declared as `application/json` in the HTTP content-type header.

### PR DESCRIPTION
**Pull request by s-l-teichmann**
Resolves #148

### CODE REVIEW

**Review by tschmidtb51 — APPROVED** [review]
LGTM and works.

**Review by bernhardreiter — DISMISSED** [review]
LGETM
(When reading the code, it would have been helpful to note even more clear that the escaper and the CreateFromFile is copying the main code from https://cs.opensource.google/go/go/+/refs/tags/go1.20:src/mime/multipart/writer.go;l=140 which is not entirely obvious as the function is called _From_ while the original is called _Form_ .)

**Review by bernhardreiter — APPROVED** [review]
LGTM

**Review by bernhard-herzog — APPROVED** [review]
LGTM.

**Pull request merged**
