### PR TITLE
Add remote validator support to downloader

### LINKED ISSUE #300: Add option for remote_validator
We should add an option in the `csaf_downloader` and `csaf_checker` to run a remote validator.

### PR DESCRIPTION
**Pull request by s-l-teichmann**
This PR adds support for remote validation in `csaf_downloader`.

This partly resolves #300

### CODE REVIEW

**Review by tschmidtb51 — DISMISSED** [review]
LGTM

**Review by tschmidtb51 — DISMISSED** [review]
LGTM and works.

**Comment by tschmidtb51** [comment]
@s-l-teichmann Please resolve the conflicts.

**Review by tschmidtb51 — APPROVED** [review]
LGTM

**Comment by tschmidtb51** [comment]
LGTM and works

**Review by bernhardreiter — APPROVED** [review]
LGTM

**Pull request merged**
