### PR TITLE
Checker: Make time range configurable to check advisories from

### PR DESCRIPTION
**Pull request by s-l-teichmann**
This is part of #394

### CODE REVIEW

**Review by ThomasJunk — APPROVED** [review]
LGTM and works

**Review by JanHoefelmeyer — APPROVED** [review]
LGTM

**Review by JanHoefelmeyer — DISMISSED** [review]
Still LGTM

**Review by JanHoefelmeyer — APPROVED** [review]
LGTM

**Review by ThomasJunk — DISMISSED** [review]
LGTM and works

**Review by JanHoefelmeyer — DISMISSED** [review]
LGTM

**Review by JanHoefelmeyer — APPROVED** [review]
LGTM

**Review by ThomasJunk — APPROVED** [review]
LGTM & works

**Pull request merged**
